/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import frame.ToDoFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sinzy
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form l_homePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new component.MyPanelCustBorder();
        btn_navIcon = new component.MyLabel();
        btn_register = new component.MyButton();
        btn_login = new component.MyButton();
        p_circle = new component.MyPanel();
        l_titleCircle = new component.MyLabel();
        l_title = new component.MyLabel();
        l_text1 = new component.MyLabel();
        l_text2 = new component.MyLabel();
        l_text3 = new component.MyLabel();
        p_footer3 = new component.MyPanelCustBorder();

        setBackground(new java.awt.Color(245, 245, 245));
        setFocusTraversalPolicyProvider(true);

        navbar.setBorderColor(new java.awt.Color(102, 102, 102));
        navbar.setBorderLeft(false);
        navbar.setBorderRight(false);
        navbar.setBorderTop(false);
        navbar.setPreferredSize(new java.awt.Dimension(1050, 50));
        navbar.setLayout(null);

        btn_navIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/todoIcon24.png"))); // NOI18N
        btn_navIcon.setText("  To-Do List");
        btn_navIcon.setColorClick(new java.awt.Color(102, 102, 102));
        btn_navIcon.setColorOver(new java.awt.Color(153, 153, 153));
        btn_navIcon.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N
        btn_navIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_navIconMouseClicked(evt);
            }
        });
        navbar.add(btn_navIcon);
        btn_navIcon.setBounds(36, 4, 171, 40);

        btn_register.setForeground(new java.awt.Color(0, 0, 0));
        btn_register.setText("Register");
        btn_register.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_register.setColor(new java.awt.Color(229, 229, 229));
        btn_register.setColorClick(new java.awt.Color(220, 220, 220));
        btn_register.setColorOver(new java.awt.Color(250, 250, 250));
        btn_register.setFont(new java.awt.Font("Gavoline", 0, 15)); // NOI18N
        btn_register.setRadius(15);
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        navbar.add(btn_register);
        btn_register.setBounds(1220, 10, 100, 30);

        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Login");
        btn_login.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_login.setColor(new java.awt.Color(229, 229, 229));
        btn_login.setColorClick(new java.awt.Color(220, 220, 220));
        btn_login.setColorOver(new java.awt.Color(250, 250, 250));
        btn_login.setFont(new java.awt.Font("Gavoline", 0, 15)); // NOI18N
        btn_login.setRadius(15);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        navbar.add(btn_login);
        btn_login.setBounds(1120, 10, 83, 30);

        p_circle.setBackgroundColor(new java.awt.Color(38, 38, 38));
        p_circle.setBorderColor(new java.awt.Color(38, 38, 38));
        p_circle.setCornerRadius(400);

        l_titleCircle.setForeground(new java.awt.Color(255, 255, 255));
        l_titleCircle.setText("To Do");
        l_titleCircle.setColor(new java.awt.Color(255, 255, 255));
        l_titleCircle.setColorClick(new java.awt.Color(255, 255, 255));
        l_titleCircle.setColorOver(new java.awt.Color(255, 255, 255));
        l_titleCircle.setFont(new java.awt.Font("Gavoline", 0, 64)); // NOI18N

        javax.swing.GroupLayout p_circleLayout = new javax.swing.GroupLayout(p_circle);
        p_circle.setLayout(p_circleLayout);
        p_circleLayout.setHorizontalGroup(
            p_circleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_circleLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(l_titleCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        p_circleLayout.setVerticalGroup(
            p_circleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_circleLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(l_titleCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        l_title.setText("To Do List");
        l_title.setColorClick(new java.awt.Color(0, 0, 0));
        l_title.setColorOver(new java.awt.Color(0, 0, 0));
        l_title.setFont(new java.awt.Font("Gavoline", 0, 72)); // NOI18N

        l_text1.setText("Solusi manajemen aktivitas sehari-hari");
        l_text1.setColorClick(new java.awt.Color(0, 0, 0));
        l_text1.setColorOver(new java.awt.Color(0, 0, 0));
        l_text1.setFont(new java.awt.Font("Gavoline", 0, 24)); // NOI18N

        l_text2.setText("untuk meningkatkan produktivitas");
        l_text2.setColorClick(new java.awt.Color(0, 0, 0));
        l_text2.setColorOver(new java.awt.Color(0, 0, 0));
        l_text2.setFont(new java.awt.Font("Gavoline", 0, 24)); // NOI18N

        l_text3.setText("anda.");
        l_text3.setColorClick(new java.awt.Color(0, 0, 0));
        l_text3.setColorOver(new java.awt.Color(0, 0, 0));
        l_text3.setFont(new java.awt.Font("Gavoline", 0, 24)); // NOI18N

        p_footer3.setBorderBottom(false);
        p_footer3.setBorderColor(new java.awt.Color(102, 102, 102));
        p_footer3.setBorderLeft(false);
        p_footer3.setBorderRight(false);
        p_footer3.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout p_footer3Layout = new javax.swing.GroupLayout(p_footer3);
        p_footer3.setLayout(p_footer3Layout);
        p_footer3Layout.setHorizontalGroup(
            p_footer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p_footer3Layout.setVerticalGroup(
            p_footer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(p_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addComponent(p_footer3, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(l_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_text2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addComponent(p_footer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showLogin();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showRegister();
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_navIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navIconMouseClicked
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showHomePage();
        }
    }//GEN-LAST:event_btn_navIconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btn_login;
    private component.MyLabel btn_navIcon;
    private component.MyButton btn_register;
    private component.MyLabel l_text1;
    private component.MyLabel l_text2;
    private component.MyLabel l_text3;
    private component.MyLabel l_title;
    private component.MyLabel l_titleCircle;
    private component.MyPanelCustBorder navbar;
    private component.MyPanel p_circle;
    private component.MyPanelCustBorder p_footer3;
    // End of variables declaration//GEN-END:variables
}
