package panel;

import frame.ToDoFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author ASUS
 */
public class Pomodoro extends javax.swing.JPanel {

    /**
     * Creates new form Pomodoro
     */
    public Pomodoro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new component.MyPanelCustBorder();
        navIcon = new component.MyLabel();
        myLabel1 = new component.MyLabel();
        myLabel2 = new component.MyLabel();
        myLabel3 = new component.MyLabel();
        jLabel1 = new javax.swing.JLabel();
        l_title = new component.MyLabel();
        p_footer3 = new component.MyPanelCustBorder();
        myLabel22 = new component.MyLabel();
        l_text1 = new component.MyLabel();
        myPanel1 = new component.MyPanel();
        btn_login = new component.MyButton();
        btn_login1 = new component.MyButton();
        btn_login2 = new component.MyButton();
        btn_login3 = new component.MyButton();
        l_title1 = new component.MyLabel();
        l_text2 = new component.MyLabel();
        myLabel15 = new component.MyLabel();
        myLabel16 = new component.MyLabel();
        l_text3 = new component.MyLabel();
        myPanel2 = new component.MyPanel();
        myLabel17 = new component.MyLabel();
        myLabel18 = new component.MyLabel();
        myLabel19 = new component.MyLabel();
        myLabel20 = new component.MyLabel();
        myPanelCustBorder1 = new component.MyPanelCustBorder();
        myLabel21 = new component.MyLabel();
        myLabel4 = new component.MyLabel();
        myLabel7 = new component.MyLabel();
        myLabel5 = new component.MyLabel();
        myLabel8 = new component.MyLabel();
        myLabel6 = new component.MyLabel();
        myLabel23 = new component.MyLabel();
        myLabel24 = new component.MyLabel();
        myLabel25 = new component.MyLabel();
        myLabel26 = new component.MyLabel();
        myPanel3 = new component.MyPanel();
        myPanel4 = new component.MyPanel();
        myLabel9 = new component.MyLabel();
        myLabel10 = new component.MyLabel();
        myPanelCustBorder2 = new component.MyPanelCustBorder();
        myLabel12 = new component.MyLabel();
        myPanel5 = new component.MyPanel();
        myLabel11 = new component.MyLabel();
        myLabel13 = new component.MyLabel();
        myPanelCustBorder3 = new component.MyPanelCustBorder();
        myLabel14 = new component.MyLabel();
        btn_addTask = new component.MyButton();

        setBackground(new java.awt.Color(245, 245, 245));
        setPreferredSize(new java.awt.Dimension(998, 700));

        navbar.setBorderBottom(false);
        navbar.setBorderColor(new java.awt.Color(102, 102, 102));
        navbar.setBorderLeft(false);
        navbar.setBorderRight(false);
        navbar.setBorderTop(false);
        navbar.setPreferredSize(new java.awt.Dimension(1050, 50));
        navbar.setLayout(null);

        navIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/todoIcon24.png"))); // NOI18N
        navIcon.setText("  Pomodoro");
        navIcon.setColorClick(new java.awt.Color(102, 102, 102));
        navIcon.setColorOver(new java.awt.Color(153, 153, 153));
        navIcon.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N
        navIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navIconMouseClicked(evt);
            }
        });
        navbar.add(navIcon);
        navIcon.setBounds(30, 10, 171, 40);

        myLabel1.setText("My Task");
        navbar.add(myLabel1);
        myLabel1.setBounds(730, 20, 52, 13);

        myLabel2.setText("Pomodoro");
        navbar.add(myLabel2);
        myLabel2.setBounds(800, 20, 60, 13);

        myLabel3.setText("Logout");
        navbar.add(myLabel3);
        myLabel3.setBounds(880, 20, 40, 13);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImageUser.png"))); // NOI18N
        navbar.add(jLabel1);
        jLabel1.setBounds(940, 10, 30, 30);

        l_title.setText("Pomodoro");
        l_title.setColorClick(new java.awt.Color(0, 0, 0));
        l_title.setColorOver(new java.awt.Color(0, 0, 0));
        l_title.setFont(new java.awt.Font("Gavoline", 0, 72)); // NOI18N

        p_footer3.setBorderBottom(false);
        p_footer3.setBorderColor(new java.awt.Color(102, 102, 102));
        p_footer3.setBorderLeft(false);
        p_footer3.setBorderRight(false);
        p_footer3.setBorderTop(false);
        p_footer3.setPreferredSize(new java.awt.Dimension(100, 50));

        myLabel22.setText("@CopyRighttodolist2025");

        javax.swing.GroupLayout p_footer3Layout = new javax.swing.GroupLayout(p_footer3);
        p_footer3.setLayout(p_footer3Layout);
        p_footer3Layout.setHorizontalGroup(
            p_footer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_footer3Layout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(myLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(424, 424, 424))
        );
        p_footer3Layout.setVerticalGroup(
            p_footer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_footer3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(myLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        l_text1.setText("Timer");
        l_text1.setColorClick(new java.awt.Color(0, 0, 0));
        l_text1.setColorOver(new java.awt.Color(0, 0, 0));
        l_text1.setFont(new java.awt.Font("Gavoline", 0, 48)); // NOI18N

        myPanel1.setBorderColor(new java.awt.Color(255, 255, 255));
        myPanel1.setCornerRadius(13);

        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Pause");
        btn_login.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_login.setColor(new java.awt.Color(245, 245, 245));
        btn_login.setColorClick(new java.awt.Color(220, 220, 220));
        btn_login.setColorOver(new java.awt.Color(250, 250, 250));
        btn_login.setFont(new java.awt.Font("Gavoline", 0, 15)); // NOI18N
        btn_login.setRadius(15);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_login1.setBorder(null);
        btn_login1.setForeground(new java.awt.Color(0, 0, 0));
        btn_login1.setText("Start");
        btn_login1.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_login1.setColor(new java.awt.Color(245, 245, 245));
        btn_login1.setColorClick(new java.awt.Color(220, 220, 220));
        btn_login1.setColorOver(new java.awt.Color(250, 250, 250));
        btn_login1.setFont(new java.awt.Font("Gavoline", 0, 15)); // NOI18N
        btn_login1.setRadius(15);
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });

        btn_login2.setForeground(new java.awt.Color(0, 0, 0));
        btn_login2.setText("Edit");
        btn_login2.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_login2.setColor(new java.awt.Color(245, 245, 245));
        btn_login2.setColorClick(new java.awt.Color(220, 220, 220));
        btn_login2.setColorOver(new java.awt.Color(250, 250, 250));
        btn_login2.setFont(new java.awt.Font("Gavoline", 0, 15)); // NOI18N
        btn_login2.setRadius(15);
        btn_login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login2ActionPerformed(evt);
            }
        });

        btn_login3.setForeground(new java.awt.Color(0, 0, 0));
        btn_login3.setText("Reset");
        btn_login3.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_login3.setColor(new java.awt.Color(245, 245, 245));
        btn_login3.setColorClick(new java.awt.Color(220, 220, 220));
        btn_login3.setColorOver(new java.awt.Color(250, 250, 250));
        btn_login3.setFont(new java.awt.Font("Gavoline", 0, 15)); // NOI18N
        btn_login3.setRadius(15);
        btn_login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login3ActionPerformed(evt);
            }
        });

        l_title1.setText("00.25.00");
        l_title1.setColorClick(new java.awt.Color(0, 0, 0));
        l_title1.setColorOver(new java.awt.Color(0, 0, 0));
        l_title1.setFont(new java.awt.Font("Gavoline", 0, 72)); // NOI18N

        l_text2.setText("00.05.00");
        l_text2.setColorClick(new java.awt.Color(0, 0, 0));
        l_text2.setColorOver(new java.awt.Color(0, 0, 0));
        l_text2.setFont(new java.awt.Font("Gavoline", 0, 24)); // NOI18N

        myLabel15.setText("Short Break");

        myLabel16.setText("Long Break");

        l_text3.setText("00.20.00");
        l_text3.setColorClick(new java.awt.Color(0, 0, 0));
        l_text3.setColorOver(new java.awt.Color(0, 0, 0));
        l_text3.setFont(new java.awt.Font("Gavoline", 0, 24)); // NOI18N

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel1Layout.createSequentialGroup()
                        .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(myPanel1Layout.createSequentialGroup()
                                .addComponent(btn_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(myPanel1Layout.createSequentialGroup()
                                .addComponent(btn_login3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_login2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(myPanel1Layout.createSequentialGroup()
                            .addComponent(myLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(174, 174, 174)
                            .addComponent(myLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(l_title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(l_title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_login3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_login2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        myPanel2.setBorderColor(new java.awt.Color(255, 255, 255));
        myPanel2.setCornerRadius(13);

        myLabel17.setText("04.05");

        myLabel18.setText("14.00");

        myLabel19.setText("3 Track, 14 min");
        myLabel19.setFont(new java.awt.Font("Gavoline", 0, 10)); // NOI18N

        myLabel20.setText("Motivation Playlist");

        myPanelCustBorder1.setBackground(new java.awt.Color(153, 255, 153));
        myPanelCustBorder1.setForeground(new java.awt.Color(153, 255, 153));

        myLabel21.setText("Music Cover");

        javax.swing.GroupLayout myPanelCustBorder1Layout = new javax.swing.GroupLayout(myPanelCustBorder1);
        myPanelCustBorder1.setLayout(myPanelCustBorder1Layout);
        myPanelCustBorder1Layout.setHorizontalGroup(
            myPanelCustBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelCustBorder1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(myLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        myPanelCustBorder1Layout.setVerticalGroup(
            myPanelCustBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelCustBorder1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(myLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        myLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\musical-note.png")); // NOI18N
        myLabel4.setText("Music Player");

        myLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\play-button.png")); // NOI18N

        myLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\next-button.png")); // NOI18N

        myLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\previous.png")); // NOI18N

        myLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\music.png")); // NOI18N

        myLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\music.png")); // NOI18N

        myLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\music.png")); // NOI18N

        myLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\music.png")); // NOI18N

        javax.swing.GroupLayout myPanel2Layout = new javax.swing.GroupLayout(myPanel2);
        myPanel2.setLayout(myPanel2Layout);
        myPanel2Layout.setHorizontalGroup(
            myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel2Layout.createSequentialGroup()
                .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(myLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(myPanel2Layout.createSequentialGroup()
                .addComponent(myLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel2Layout.createSequentialGroup()
                        .addComponent(myLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel2Layout.createSequentialGroup()
                        .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(myPanel2Layout.createSequentialGroup()
                                .addComponent(myLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(myLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(myLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(myPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(myLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(myPanelCustBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
        );
        myPanel2Layout.setVerticalGroup(
            myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myPanelCustBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(myLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(myLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        myPanel3.setBorderColor(new java.awt.Color(255, 255, 255));
        myPanel3.setCornerRadius(13);

        myPanel4.setBorderColor(new java.awt.Color(242, 242, 242));
        myPanel4.setCornerRadius(20);

        myLabel9.setText("Surat Cinta Untuk Starla");

        myLabel10.setText("Virgoun");

        myPanelCustBorder2.setBackgroundColor(new java.awt.Color(229, 229, 229));
        myPanelCustBorder2.setBorderBottom(false);
        myPanelCustBorder2.setBorderLeft(false);
        myPanelCustBorder2.setBorderRight(false);
        myPanelCustBorder2.setBorderTop(false);
        myPanelCustBorder2.setCornerRadius(1000);

        myLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N

        javax.swing.GroupLayout myPanelCustBorder2Layout = new javax.swing.GroupLayout(myPanelCustBorder2);
        myPanelCustBorder2.setLayout(myPanelCustBorder2Layout);
        myPanelCustBorder2Layout.setHorizontalGroup(
            myPanelCustBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelCustBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        myPanelCustBorder2Layout.setVerticalGroup(
            myPanelCustBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelCustBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout myPanel4Layout = new javax.swing.GroupLayout(myPanel4);
        myPanel4.setLayout(myPanel4Layout);
        myPanel4Layout.setHorizontalGroup(
            myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myPanelCustBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        myPanel4Layout.setVerticalGroup(
            myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myPanelCustBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(myPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(myLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        myPanel5.setBorderColor(new java.awt.Color(242, 242, 242));
        myPanel5.setCornerRadius(20);

        myLabel11.setText("Love Yourself");

        myLabel13.setText("Justien Bieber");

        myPanelCustBorder3.setBackgroundColor(new java.awt.Color(229, 229, 229));
        myPanelCustBorder3.setBorderBottom(false);
        myPanelCustBorder3.setBorderLeft(false);
        myPanelCustBorder3.setBorderRight(false);
        myPanelCustBorder3.setBorderTop(false);
        myPanelCustBorder3.setCornerRadius(1000);

        myLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N

        javax.swing.GroupLayout myPanelCustBorder3Layout = new javax.swing.GroupLayout(myPanelCustBorder3);
        myPanelCustBorder3.setLayout(myPanelCustBorder3Layout);
        myPanelCustBorder3Layout.setHorizontalGroup(
            myPanelCustBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelCustBorder3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        myPanelCustBorder3Layout.setVerticalGroup(
            myPanelCustBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelCustBorder3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout myPanel5Layout = new javax.swing.GroupLayout(myPanel5);
        myPanel5.setLayout(myPanel5Layout);
        myPanel5Layout.setHorizontalGroup(
            myPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(myPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myPanelCustBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        myPanel5Layout.setVerticalGroup(
            myPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(myPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myPanelCustBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(myPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(myLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btn_addTask.setBackground(new java.awt.Color(0, 0, 0));
        btn_addTask.setForeground(new java.awt.Color(255, 255, 255));
        btn_addTask.setText("+ Add Music");
        btn_addTask.setBorderColor(new java.awt.Color(0, 0, 0));
        btn_addTask.setColor(java.awt.Color.black);
        btn_addTask.setColorClick(new java.awt.Color(51, 51, 51));
        btn_addTask.setColorOver(new java.awt.Color(51, 51, 51));
        btn_addTask.setRadius(5);
        btn_addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanel3Layout = new javax.swing.GroupLayout(myPanel3);
        myPanel3.setLayout(myPanel3Layout);
        myPanel3Layout.setHorizontalGroup(
            myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        myPanel3Layout.setVerticalGroup(
            myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(btn_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(p_footer3, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(myPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(l_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(myPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(myPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(myPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(p_footer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void navIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navIconMouseClicked
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showHomePage();
        }
    }//GEN-LAST:event_navIconMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showLogin();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_login1ActionPerformed

    private void btn_login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_login2ActionPerformed

    private void btn_login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_login3ActionPerformed

    private void btn_addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTaskActionPerformed
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showTambahToDoList();
        }
    }//GEN-LAST:event_btn_addTaskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyButton btn_addTask;
    private component.MyButton btn_login;
    private component.MyButton btn_login1;
    private component.MyButton btn_login2;
    private component.MyButton btn_login3;
    private javax.swing.JLabel jLabel1;
    private component.MyLabel l_text1;
    private component.MyLabel l_text2;
    private component.MyLabel l_text3;
    private component.MyLabel l_title;
    private component.MyLabel l_title1;
    private component.MyLabel myLabel1;
    private component.MyLabel myLabel10;
    private component.MyLabel myLabel11;
    private component.MyLabel myLabel12;
    private component.MyLabel myLabel13;
    private component.MyLabel myLabel14;
    private component.MyLabel myLabel15;
    private component.MyLabel myLabel16;
    private component.MyLabel myLabel17;
    private component.MyLabel myLabel18;
    private component.MyLabel myLabel19;
    private component.MyLabel myLabel2;
    private component.MyLabel myLabel20;
    private component.MyLabel myLabel21;
    private component.MyLabel myLabel22;
    private component.MyLabel myLabel23;
    private component.MyLabel myLabel24;
    private component.MyLabel myLabel25;
    private component.MyLabel myLabel26;
    private component.MyLabel myLabel3;
    private component.MyLabel myLabel4;
    private component.MyLabel myLabel5;
    private component.MyLabel myLabel6;
    private component.MyLabel myLabel7;
    private component.MyLabel myLabel8;
    private component.MyLabel myLabel9;
    private component.MyPanel myPanel1;
    private component.MyPanel myPanel2;
    private component.MyPanel myPanel3;
    private component.MyPanel myPanel4;
    private component.MyPanel myPanel5;
    private component.MyPanelCustBorder myPanelCustBorder1;
    private component.MyPanelCustBorder myPanelCustBorder2;
    private component.MyPanelCustBorder myPanelCustBorder3;
    private component.MyLabel navIcon;
    private component.MyPanelCustBorder navbar;
    private component.MyPanelCustBorder p_footer3;
    // End of variables declaration//GEN-END:variables
}
