package panel;

import frame.ToDoFrame;
import javax.swing.SwingUtilities;

public class TambahToDoList extends javax.swing.JPanel {

    /**
     * Creates new form TambahTask
     */
    public TambahToDoList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new component.MyPanelCustBorder();
        btn_navIcon = new component.MyLabel();
        myLabel1 = new component.MyLabel();
        myLabel2 = new component.MyLabel();
        myLabel3 = new component.MyLabel();
        jLabel1 = new javax.swing.JLabel();
        footer = new component.MyPanelCustBorder();
        myLabel8 = new component.MyLabel();
        myTextFieldCustBorder1 = new component.MyTextFieldCustBorder();
        myLabel4 = new component.MyLabel();
        myLabel5 = new component.MyLabel();
        myTextFieldCustBorder2 = new component.MyTextFieldCustBorder();
        myLabel6 = new component.MyLabel();
        myTextFieldCustBorder3 = new component.MyTextFieldCustBorder();
        myTextFieldCustBorder4 = new component.MyTextFieldCustBorder();
        myLabel7 = new component.MyLabel();
        myButton1 = new component.MyButton();

        setBackground(new java.awt.Color(245, 245, 245));

        navbar.setBorderBottom(false);
        navbar.setBorderColor(new java.awt.Color(102, 102, 102));
        navbar.setBorderLeft(false);
        navbar.setBorderRight(false);
        navbar.setBorderTop(false);
        navbar.setPreferredSize(new java.awt.Dimension(1050, 50));
        navbar.setLayout(null);

        btn_navIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/todoIcon24.png"))); // NOI18N
        btn_navIcon.setText("  Tambah-Do List");
        btn_navIcon.setColorClick(new java.awt.Color(102, 102, 102));
        btn_navIcon.setColorOver(new java.awt.Color(153, 153, 153));
        btn_navIcon.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N
        btn_navIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_navIconMouseClicked(evt);
            }
        });
        navbar.add(btn_navIcon);
        btn_navIcon.setBounds(36, 4, 180, 40);

        myLabel1.setText("My Task");
        navbar.add(myLabel1);
        myLabel1.setBounds(830, 20, 52, 13);

        myLabel2.setText("Pomodoro");
        navbar.add(myLabel2);
        myLabel2.setBounds(900, 20, 60, 13);

        myLabel3.setText("Logout");
        navbar.add(myLabel3);
        myLabel3.setBounds(990, 20, 40, 13);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ImageUser.png"))); // NOI18N
        navbar.add(jLabel1);
        jLabel1.setBounds(1050, 10, 30, 30);

        footer.setBorderBottom(false);
        footer.setBorderLeft(false);
        footer.setBorderRight(false);
        footer.setBorderTop(false);
        footer.setPreferredSize(new java.awt.Dimension(100, 50));

        myLabel8.setText("@copyrighttodolist2025");
        myLabel8.setColorClick(new java.awt.Color(0, 0, 0));
        myLabel8.setColorOver(new java.awt.Color(0, 0, 0));
        myLabel8.setFont(new java.awt.Font("Gavoline", 0, 14)); // NOI18N

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(myLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        myTextFieldCustBorder1.setCornerRadius(10);

        myLabel4.setText("Nama Project");
        myLabel4.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N

        myLabel5.setText("Nama Project");
        myLabel5.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N

        myTextFieldCustBorder2.setCornerRadius(10);
        myTextFieldCustBorder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTextFieldCustBorder2ActionPerformed(evt);
            }
        });

        myLabel6.setText("Nama Project");
        myLabel6.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N

        myTextFieldCustBorder3.setCornerRadius(10);

        myTextFieldCustBorder4.setCornerRadius(10);

        myLabel7.setText("Nama Project");
        myLabel7.setFont(new java.awt.Font("Gavoline", 0, 18)); // NOI18N

        myButton1.setBackground(new java.awt.Color(0, 0, 0));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Simpan");
        myButton1.setBorderColor(new java.awt.Color(0, 0, 0));
        myButton1.setColor(java.awt.Color.black);
        myButton1.setColorClick(new java.awt.Color(51, 51, 51));
        myButton1.setColorOver(new java.awt.Color(51, 51, 51));
        myButton1.setRadius(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(myTextFieldCustBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myTextFieldCustBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myTextFieldCustBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myTextFieldCustBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(myLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myTextFieldCustBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myTextFieldCustBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myTextFieldCustBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myTextFieldCustBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_navIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_navIconMouseClicked
        ToDoFrame toDoFrame = (ToDoFrame) SwingUtilities.getWindowAncestor(this);
        if (toDoFrame != null) {
            toDoFrame.showHomePage();
        }
    }//GEN-LAST:event_btn_navIconMouseClicked

    private void myTextFieldCustBorder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTextFieldCustBorder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myTextFieldCustBorder2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.MyLabel btn_navIcon;
    private component.MyPanelCustBorder footer;
    private javax.swing.JLabel jLabel1;
    private component.MyButton myButton1;
    private component.MyLabel myLabel1;
    private component.MyLabel myLabel2;
    private component.MyLabel myLabel3;
    private component.MyLabel myLabel4;
    private component.MyLabel myLabel5;
    private component.MyLabel myLabel6;
    private component.MyLabel myLabel7;
    private component.MyLabel myLabel8;
    private component.MyTextFieldCustBorder myTextFieldCustBorder1;
    private component.MyTextFieldCustBorder myTextFieldCustBorder2;
    private component.MyTextFieldCustBorder myTextFieldCustBorder3;
    private component.MyTextFieldCustBorder myTextFieldCustBorder4;
    private component.MyPanelCustBorder navbar;
    // End of variables declaration//GEN-END:variables
}
